#!/bin/sh -e

usage() {
  echo "Usage: $(basename "$0") distribution package"
  exit 1
}

if [ -z "$1" ] || [ -z "$2" ]; then
  usage
fi

DISTRIBUTION=$1
PACKAGE=$2

reprepro --ask-passphrase --verbose --basedir "${DISTRIBUTION}" includedeb "${DISTRIBUTION}" "${PACKAGE}"

echo
reprepro --basedir "${DISTRIBUTION}" list "${DISTRIBUTION}"
echo
echo "$(basename "${PACKAGE}") added."

./createPackageList

git add . >/dev/null 2>&1
git commit -m "add package $(basename "${PACKAGE}") to ${DISTRIBUTION}"
git push
