#!/bin/sh

# sudo reprepro -Vb /var/www/html/apt --component=contrib includedeb trusty /tmp/deb/contrib/dp_1.0_all.deb

usage(){
    echo "Usage: $(basename $0) distribution package"
    exit 1
}

if [ -z "$1" ] || [ -z "$2" ]; then
    usage
fi

DISTRIBUTION=$1
PACKAGE=$2

sudo reprepro --ask-passphrase -Vb $DISTRIBUTION includedeb $@
sudo chown --recursive $USER.$USER $DISTRIBUTION

echo
reprepro -b $DISTRIBUTION list $DISTRIBUTION
echo
echo "$(basename $PACKAGE) added."

echo "| Distribution | Components | Architecture | Package | Version |" > PACKAGES.md
echo "| ------------ | ------ | -------- | ------- | ------- |" >> PACKAGES.md
show(){
	./lspkg $1|sed 's/: /|/g;s/ /|/g' | awk '{print "|" $0 "|"}' >> PACKAGES.md
}
show trusty
show xenial
show jessie
show stretch

git add . > /dev/null 2>&1
git commit -m "add package $( basename ${PACKAGE} ) to ${DISTRIBUTION}"
git push