#!/bin/sh -e

listDistro() {
  reprepro --basedir "$1" list "$1" | sed 's/: /|/g;s/ /|/g' | awk '{print "|" $0 "|"}' >>PACKAGES.md
}

{
  echo "## List of packages"
  echo ""
  echo "| Distribution | Component | Architecture | Package | Version |"
  echo "| ------------ | ------ | -------- | ------- | ------- |"
} >PACKAGES.md

for dir in */; do
  listDistro "$(echo "$dir" | sed 's|/||g')"
done
