#!/bin/sh -e

usage() {
  echo "Usage: $(basename "$0") distribution package"
  exit 1
}

if [ -z "$1" ] || [ -z "$2" ]; then
  usage
fi

DISTRIBUTION=$1
PACKAGE=$2

reprepro --basedir "${DISTRIBUTION}" remove "${DISTRIBUTION}" "${PACKAGE}"

./createPackageList

git add . >/dev/null 2>&1
git commit -m "delete package $(basename "${PACKAGE}") from ${DISTRIBUTION}"
git push
